### ISSUE TITLE
Búsqueda parcial por nombre

### ISSUE THREAD

**Issue by jgbernalp** [ValentinaBacherer/SP2-Hackathon#2]
Para hacer el filtro por solo las letras iniciales o alguna sub cadena dentro del nombre puedes usar https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

https://github.com/ValentinaBacherer/SP2-Hackathon/blob/e9cee4b3ac973565a4b5d23d259a03f09772469d/usersService.js#L66

**Comment by jgbernalp** [comment]
En general los errores pueden pasar tanto en el cliente como en el servidor. El cliente (navegador) debe informar al usuario del error que sucedió. En el lado del servidor generalmente se retorna un HTTP status que le informa al cliente sobre los errores y se crea una entrada en el log del servidor. (console.log)

Cuando el API no tiene resultados de la búsqueda debería enviar un array vacío, esto no es un error simplemente no hubo resultados para el criterio de búsqueda. Si hay un error en el servidor entonces si se envía un error de tipo 5XX (500, 501, etc). O si el cliente envió mal la información sería uno de tipo 4XX(401,403, etc) 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by jgbernalp** [comment]
@ValentinaBacherer 👆🏽

**Comment by ValentinaBacherer** [comment]
Done
https://github.com/ValentinaBacherer/SP2-Hackathon/pull/new/newFilter
